---
- name: "Create service {{ service_name }}"
  shell: "docker service create --replicas {{ service_replicas }} -p {{ service_port }} --name {{ service_name }} --update-delay 10s {{ service_image }}:{{ service_version }}"